- name: Disable swap immediately
  ansible.builtin.command: swapoff -a
  become: yes

- name: Comment out swap entries in /etc/fstab to disable swap permanently
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+)'
    replace: '# \1'
  become: yes

- name: Remove ZRAM on RedHat-based Linux
  become: yes
  ansible.builtin.sudo dnf:
    name:   zram-generator-defaults
    state:  absent
  when: ansible_os_family == "RedHat"